// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/carlosgab83/matrix/go/internal/shared/domain"

	mock "github.com/stretchr/testify/mock"
)

// IngestorServiceInterface is an autogenerated mock type for the IngestorServiceInterface type
type IngestorServiceInterface struct {
	mock.Mock
}

type IngestorServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *IngestorServiceInterface) EXPECT() *IngestorServiceInterface_Expecter {
	return &IngestorServiceInterface_Expecter{mock: &_m.Mock}
}

// IngestPrice provides a mock function with given fields: price
func (_m *IngestorServiceInterface) IngestPrice(price *domain.Price) error {
	ret := _m.Called(price)

	if len(ret) == 0 {
		panic("no return value specified for IngestPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Price) error); ok {
		r0 = rf(price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngestorServiceInterface_IngestPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestPrice'
type IngestorServiceInterface_IngestPrice_Call struct {
	*mock.Call
}

// IngestPrice is a helper method to define mock.On call
//   - price *domain.Price
func (_e *IngestorServiceInterface_Expecter) IngestPrice(price interface{}) *IngestorServiceInterface_IngestPrice_Call {
	return &IngestorServiceInterface_IngestPrice_Call{Call: _e.mock.On("IngestPrice", price)}
}

func (_c *IngestorServiceInterface_IngestPrice_Call) Run(run func(price *domain.Price)) *IngestorServiceInterface_IngestPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Price))
	})
	return _c
}

func (_c *IngestorServiceInterface_IngestPrice_Call) Return(_a0 error) *IngestorServiceInterface_IngestPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngestorServiceInterface_IngestPrice_Call) RunAndReturn(run func(*domain.Price) error) *IngestorServiceInterface_IngestPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngestorServiceInterface creates a new instance of IngestorServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestorServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngestorServiceInterface {
	mock := &IngestorServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
