// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/carlosgab83/matrix/go/internal/shared/domain"

	mock "github.com/stretchr/testify/mock"
)

// Ingestor is an autogenerated mock type for the Ingestor type
type Ingestor struct {
	mock.Mock
}

type Ingestor_Expecter struct {
	mock *mock.Mock
}

func (_m *Ingestor) EXPECT() *Ingestor_Expecter {
	return &Ingestor_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Ingestor) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ingestor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Ingestor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Ingestor_Expecter) Close() *Ingestor_Close_Call {
	return &Ingestor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Ingestor_Close_Call) Run(run func()) *Ingestor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Ingestor_Close_Call) Return(_a0 error) *Ingestor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Ingestor_Close_Call) RunAndReturn(run func() error) *Ingestor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IngestPrice provides a mock function with given fields: _a0, _a1
func (_m *Ingestor) IngestPrice(_a0 context.Context, _a1 *domain.Price) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IngestPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Price) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ingestor_IngestPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestPrice'
type Ingestor_IngestPrice_Call struct {
	*mock.Call
}

// IngestPrice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *domain.Price
func (_e *Ingestor_Expecter) IngestPrice(_a0 interface{}, _a1 interface{}) *Ingestor_IngestPrice_Call {
	return &Ingestor_IngestPrice_Call{Call: _e.mock.On("IngestPrice", _a0, _a1)}
}

func (_c *Ingestor_IngestPrice_Call) Run(run func(_a0 context.Context, _a1 *domain.Price)) *Ingestor_IngestPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Price))
	})
	return _c
}

func (_c *Ingestor_IngestPrice_Call) Return(_a0 error) *Ingestor_IngestPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Ingestor_IngestPrice_Call) RunAndReturn(run func(context.Context, *domain.Price) error) *Ingestor_IngestPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngestor creates a new instance of Ingestor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ingestor {
	mock := &Ingestor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
