// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

type Notifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifier) EXPECT() *Notifier_Expecter {
	return &Notifier_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Notifier) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Notifier_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Notifier_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Notifier_Expecter) Close() *Notifier_Close_Call {
	return &Notifier_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Notifier_Close_Call) Run(run func()) *Notifier_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Notifier_Close_Call) Return(_a0 error) *Notifier_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notifier_Close_Call) RunAndReturn(run func() error) *Notifier_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function with given fields: ctx, chatID, payload
func (_m *Notifier) Notify(ctx context.Context, chatID string, payload string) error {
	ret := _m.Called(ctx, chatID, payload)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, chatID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Notifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type Notifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - payload string
func (_e *Notifier_Expecter) Notify(ctx interface{}, chatID interface{}, payload interface{}) *Notifier_Notify_Call {
	return &Notifier_Notify_Call{Call: _e.mock.On("Notify", ctx, chatID, payload)}
}

func (_c *Notifier_Notify_Call) Run(run func(ctx context.Context, chatID string, payload string)) *Notifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Notifier_Notify_Call) Return(_a0 error) *Notifier_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notifier_Notify_Call) RunAndReturn(run func(context.Context, string, string) error) *Notifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: _a0
func (_m *Notifier) Register(_a0 context.Context) {
	_m.Called(_a0)
}

// Notifier_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Notifier_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Notifier_Expecter) Register(_a0 interface{}) *Notifier_Register_Call {
	return &Notifier_Register_Call{Call: _e.mock.On("Register", _a0)}
}

func (_c *Notifier_Register_Call) Run(run func(_a0 context.Context)) *Notifier_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Notifier_Register_Call) Return() *Notifier_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Notifier_Register_Call) RunAndReturn(run func(context.Context)) *Notifier_Register_Call {
	_c.Run(run)
	return _c
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
