// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	matrix_proto "github.com/carlosgab83/matrix/go/internal/shared/proto/matrix.proto"
	mock "github.com/stretchr/testify/mock"
)

// PriceIngestorClient is an autogenerated mock type for the PriceIngestorClient type
type PriceIngestorClient struct {
	mock.Mock
}

type PriceIngestorClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceIngestorClient) EXPECT() *PriceIngestorClient_Expecter {
	return &PriceIngestorClient_Expecter{mock: &_m.Mock}
}

// IngestPrice provides a mock function with given fields: ctx, opts
func (_m *PriceIngestorClient) IngestPrice(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for IngestPrice")
	}

	var r0 grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceIngestorClient_IngestPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestPrice'
type PriceIngestorClient_IngestPrice_Call struct {
	*mock.Call
}

// IngestPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *PriceIngestorClient_Expecter) IngestPrice(ctx interface{}, opts ...interface{}) *PriceIngestorClient_IngestPrice_Call {
	return &PriceIngestorClient_IngestPrice_Call{Call: _e.mock.On("IngestPrice",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *PriceIngestorClient_IngestPrice_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *PriceIngestorClient_IngestPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PriceIngestorClient_IngestPrice_Call) Return(_a0 grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse], _a1 error) *PriceIngestorClient_IngestPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceIngestorClient_IngestPrice_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[matrix_proto.PriceMessage, matrix_proto.IngestResponse], error)) *PriceIngestorClient_IngestPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewPriceIngestorClient creates a new instance of PriceIngestorClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceIngestorClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceIngestorClient {
	mock := &PriceIngestorClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
