// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	matrix_proto "github.com/carlosgab83/matrix/go/internal/shared/proto/matrix.proto"
	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// PriceIngestor_IngestPriceClient is an autogenerated mock type for the PriceIngestor_IngestPriceClient type
type PriceIngestor_IngestPriceClient[Req interface{}, Res interface{}] struct {
	mock.Mock
}

type PriceIngestor_IngestPriceClient_Expecter[Req interface{}, Res interface{}] struct {
	mock *mock.Mock
}

func (_m *PriceIngestor_IngestPriceClient[Req, Res]) EXPECT() *PriceIngestor_IngestPriceClient_Expecter[Req, Res] {
	return &PriceIngestor_IngestPriceClient_Expecter[Req, Res]{mock: &_m.Mock}
}

// CloseAndRecv provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) CloseAndRecv() (*matrix_proto.IngestResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAndRecv")
	}

	var r0 *matrix_proto.IngestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*matrix_proto.IngestResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *matrix_proto.IngestResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matrix_proto.IngestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceIngestor_IngestPriceClient_CloseAndRecv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAndRecv'
type PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// CloseAndRecv is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) CloseAndRecv() *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res]{Call: _e.mock.On("CloseAndRecv")}
}

func (_c *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res]) Return(_a0 *matrix_proto.IngestResponse, _a1 error) *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res]) RunAndReturn(run func() (*matrix_proto.IngestResponse, error)) *PriceIngestor_IngestPriceClient_CloseAndRecv_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// CloseSend provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) CloseSend() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type PriceIngestor_IngestPriceClient_CloseSend_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) CloseSend() *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res]{Call: _e.mock.On("CloseSend")}
}

func (_c *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res]) RunAndReturn(run func() error) *PriceIngestor_IngestPriceClient_CloseSend_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// PriceIngestor_IngestPriceClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type PriceIngestor_IngestPriceClient_Context_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) Context() *PriceIngestor_IngestPriceClient_Context_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_Context_Call[Req, Res]{Call: _e.mock.On("Context")}
}

func (_c *PriceIngestor_IngestPriceClient_Context_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceClient_Context_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Context_Call[Req, Res]) Return(_a0 context.Context) *PriceIngestor_IngestPriceClient_Context_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Context_Call[Req, Res]) RunAndReturn(run func() context.Context) *PriceIngestor_IngestPriceClient_Context_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) Header() (metadata.MD, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceIngestor_IngestPriceClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type PriceIngestor_IngestPriceClient_Header_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) Header() *PriceIngestor_IngestPriceClient_Header_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_Header_Call[Req, Res]{Call: _e.mock.On("Header")}
}

func (_c *PriceIngestor_IngestPriceClient_Header_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceClient_Header_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Header_Call[Req, Res]) Return(_a0 metadata.MD, _a1 error) *PriceIngestor_IngestPriceClient_Header_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Header_Call[Req, Res]) RunAndReturn(run func() (metadata.MD, error)) *PriceIngestor_IngestPriceClient_Header_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type PriceIngestor_IngestPriceClient_RecvMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) RecvMsg(m interface{}) *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res]{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res]) Run(run func(m interface{})) *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *PriceIngestor_IngestPriceClient_RecvMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) Send(_a0 *matrix_proto.PriceMessage) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*matrix_proto.PriceMessage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type PriceIngestor_IngestPriceClient_Send_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *matrix_proto.PriceMessage
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) Send(_a0 interface{}) *PriceIngestor_IngestPriceClient_Send_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_Send_Call[Req, Res]{Call: _e.mock.On("Send", _a0)}
}

func (_c *PriceIngestor_IngestPriceClient_Send_Call[Req, Res]) Run(run func(_a0 *matrix_proto.PriceMessage)) *PriceIngestor_IngestPriceClient_Send_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*matrix_proto.PriceMessage))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Send_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceClient_Send_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Send_Call[Req, Res]) RunAndReturn(run func(*matrix_proto.PriceMessage) error) *PriceIngestor_IngestPriceClient_Send_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type PriceIngestor_IngestPriceClient_SendMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) SendMsg(m interface{}) *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res]{Call: _e.mock.On("SendMsg", m)}
}

func (_c *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res]) Run(run func(m interface{})) *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *PriceIngestor_IngestPriceClient_SendMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceClient[Req, Res]) Trailer() metadata.MD {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// PriceIngestor_IngestPriceClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type PriceIngestor_IngestPriceClient_Trailer_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceClient_Expecter[Req, Res]) Trailer() *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res] {
	return &PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res]{Call: _e.mock.On("Trailer")}
}

func (_c *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res]) Return(_a0 metadata.MD) *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res]) RunAndReturn(run func() metadata.MD) *PriceIngestor_IngestPriceClient_Trailer_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// NewPriceIngestor_IngestPriceClient creates a new instance of PriceIngestor_IngestPriceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceIngestor_IngestPriceClient[Req interface{}, Res interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceIngestor_IngestPriceClient[Req, Res] {
	mock := &PriceIngestor_IngestPriceClient[Req, Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
