// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	matrix_proto "github.com/carlosgab83/matrix/go/internal/shared/proto/matrix.proto"
	metadata "google.golang.org/grpc/metadata"

	mock "github.com/stretchr/testify/mock"
)

// PriceIngestor_IngestPriceServer is an autogenerated mock type for the PriceIngestor_IngestPriceServer type
type PriceIngestor_IngestPriceServer[Req interface{}, Res interface{}] struct {
	mock.Mock
}

type PriceIngestor_IngestPriceServer_Expecter[Req interface{}, Res interface{}] struct {
	mock *mock.Mock
}

func (_m *PriceIngestor_IngestPriceServer[Req, Res]) EXPECT() *PriceIngestor_IngestPriceServer_Expecter[Req, Res] {
	return &PriceIngestor_IngestPriceServer_Expecter[Req, Res]{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// PriceIngestor_IngestPriceServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type PriceIngestor_IngestPriceServer_Context_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) Context() *PriceIngestor_IngestPriceServer_Context_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_Context_Call[Req, Res]{Call: _e.mock.On("Context")}
}

func (_c *PriceIngestor_IngestPriceServer_Context_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceServer_Context_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_Context_Call[Req, Res]) Return(_a0 context.Context) *PriceIngestor_IngestPriceServer_Context_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_Context_Call[Req, Res]) RunAndReturn(run func() context.Context) *PriceIngestor_IngestPriceServer_Context_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with no fields
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) Recv() (*matrix_proto.PriceMessage, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *matrix_proto.PriceMessage
	var r1 error
	if rf, ok := ret.Get(0).(func() (*matrix_proto.PriceMessage, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *matrix_proto.PriceMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matrix_proto.PriceMessage)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PriceIngestor_IngestPriceServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type PriceIngestor_IngestPriceServer_Recv_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) Recv() *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_Recv_Call[Req, Res]{Call: _e.mock.On("Recv")}
}

func (_c *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res]) Run(run func()) *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res]) Return(_a0 *matrix_proto.PriceMessage, _a1 error) *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res]) RunAndReturn(run func() (*matrix_proto.PriceMessage, error)) *PriceIngestor_IngestPriceServer_Recv_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type PriceIngestor_IngestPriceServer_RecvMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) RecvMsg(m interface{}) *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res]{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res]) Run(run func(m interface{})) *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *PriceIngestor_IngestPriceServer_RecvMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendAndClose provides a mock function with given fields: _a0
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) SendAndClose(_a0 *matrix_proto.IngestResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendAndClose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*matrix_proto.IngestResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceServer_SendAndClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAndClose'
type PriceIngestor_IngestPriceServer_SendAndClose_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendAndClose is a helper method to define mock.On call
//   - _a0 *matrix_proto.IngestResponse
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) SendAndClose(_a0 interface{}) *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res]{Call: _e.mock.On("SendAndClose", _a0)}
}

func (_c *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res]) Run(run func(_a0 *matrix_proto.IngestResponse)) *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*matrix_proto.IngestResponse))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res]) RunAndReturn(run func(*matrix_proto.IngestResponse) error) *PriceIngestor_IngestPriceServer_SendAndClose_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type PriceIngestor_IngestPriceServer_SendHeader_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) SendHeader(_a0 interface{}) *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res]{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res]) Run(run func(_a0 metadata.MD)) *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res]) RunAndReturn(run func(metadata.MD) error) *PriceIngestor_IngestPriceServer_SendHeader_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type PriceIngestor_IngestPriceServer_SendMsg_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) SendMsg(m interface{}) *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res]{Call: _e.mock.On("SendMsg", m)}
}

func (_c *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res]) Run(run func(m interface{})) *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res]) RunAndReturn(run func(interface{}) error) *PriceIngestor_IngestPriceServer_SendMsg_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestor_IngestPriceServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type PriceIngestor_IngestPriceServer_SetHeader_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) SetHeader(_a0 interface{}) *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res]{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res]) Run(run func(_a0 metadata.MD)) *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res]) Return(_a0 error) *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res]) RunAndReturn(run func(metadata.MD) error) *PriceIngestor_IngestPriceServer_SetHeader_Call[Req, Res] {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *PriceIngestor_IngestPriceServer[Req, Res]) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// PriceIngestor_IngestPriceServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type PriceIngestor_IngestPriceServer_SetTrailer_Call[Req interface{}, Res interface{}] struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *PriceIngestor_IngestPriceServer_Expecter[Req, Res]) SetTrailer(_a0 interface{}) *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res] {
	return &PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res]{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res]) Run(run func(_a0 metadata.MD)) *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res]) Return() *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res] {
	_c.Call.Return()
	return _c
}

func (_c *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res]) RunAndReturn(run func(metadata.MD)) *PriceIngestor_IngestPriceServer_SetTrailer_Call[Req, Res] {
	_c.Run(run)
	return _c
}

// NewPriceIngestor_IngestPriceServer creates a new instance of PriceIngestor_IngestPriceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceIngestor_IngestPriceServer[Req interface{}, Res interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceIngestor_IngestPriceServer[Req, Res] {
	mock := &PriceIngestor_IngestPriceServer[Req, Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
