// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/carlosgab83/matrix/go/internal/shared/domain"
	mock "github.com/stretchr/testify/mock"
)

// PriceRepository is an autogenerated mock type for the PriceRepository type
type PriceRepository struct {
	mock.Mock
}

type PriceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceRepository) EXPECT() *PriceRepository_Expecter {
	return &PriceRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *PriceRepository) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type PriceRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *PriceRepository_Expecter) Close() *PriceRepository_Close_Call {
	return &PriceRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *PriceRepository_Close_Call) Run(run func()) *PriceRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceRepository_Close_Call) Return(_a0 error) *PriceRepository_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceRepository_Close_Call) RunAndReturn(run func() error) *PriceRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPrice provides a mock function with given fields: _a0, _a1
func (_m *PriceRepository) InsertPrice(_a0 context.Context, _a1 domain.Price) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Price) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceRepository_InsertPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPrice'
type PriceRepository_InsertPrice_Call struct {
	*mock.Call
}

// InsertPrice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Price
func (_e *PriceRepository_Expecter) InsertPrice(_a0 interface{}, _a1 interface{}) *PriceRepository_InsertPrice_Call {
	return &PriceRepository_InsertPrice_Call{Call: _e.mock.On("InsertPrice", _a0, _a1)}
}

func (_c *PriceRepository_InsertPrice_Call) Run(run func(_a0 context.Context, _a1 domain.Price)) *PriceRepository_InsertPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Price))
	})
	return _c
}

func (_c *PriceRepository_InsertPrice_Call) Return(_a0 error) *PriceRepository_InsertPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceRepository_InsertPrice_Call) RunAndReturn(run func(context.Context, domain.Price) error) *PriceRepository_InsertPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewPriceRepository creates a new instance of PriceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceRepository {
	mock := &PriceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
