// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	matrix_proto "github.com/carlosgab83/matrix/go/internal/shared/proto/matrix.proto"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// PriceIngestorServer is an autogenerated mock type for the PriceIngestorServer type
type PriceIngestorServer struct {
	mock.Mock
}

type PriceIngestorServer_Expecter struct {
	mock *mock.Mock
}

func (_m *PriceIngestorServer) EXPECT() *PriceIngestorServer_Expecter {
	return &PriceIngestorServer_Expecter{mock: &_m.Mock}
}

// IngestPrice provides a mock function with given fields: _a0
func (_m *PriceIngestorServer) IngestPrice(_a0 grpc.ClientStreamingServer[matrix_proto.PriceMessage, matrix_proto.IngestResponse]) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for IngestPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(grpc.ClientStreamingServer[matrix_proto.PriceMessage, matrix_proto.IngestResponse]) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PriceIngestorServer_IngestPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestPrice'
type PriceIngestorServer_IngestPrice_Call struct {
	*mock.Call
}

// IngestPrice is a helper method to define mock.On call
//   - _a0 grpc.ClientStreamingServer[matrix_proto.PriceMessage,matrix_proto.IngestResponse]
func (_e *PriceIngestorServer_Expecter) IngestPrice(_a0 interface{}) *PriceIngestorServer_IngestPrice_Call {
	return &PriceIngestorServer_IngestPrice_Call{Call: _e.mock.On("IngestPrice", _a0)}
}

func (_c *PriceIngestorServer_IngestPrice_Call) Run(run func(_a0 grpc.ClientStreamingServer[matrix_proto.PriceMessage, matrix_proto.IngestResponse])) *PriceIngestorServer_IngestPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(grpc.ClientStreamingServer[matrix_proto.PriceMessage, matrix_proto.IngestResponse]))
	})
	return _c
}

func (_c *PriceIngestorServer_IngestPrice_Call) Return(_a0 error) *PriceIngestorServer_IngestPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PriceIngestorServer_IngestPrice_Call) RunAndReturn(run func(grpc.ClientStreamingServer[matrix_proto.PriceMessage, matrix_proto.IngestResponse]) error) *PriceIngestorServer_IngestPrice_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedPriceIngestorServer provides a mock function with no fields
func (_m *PriceIngestorServer) mustEmbedUnimplementedPriceIngestorServer() {
	_m.Called()
}

// PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPriceIngestorServer'
type PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPriceIngestorServer is a helper method to define mock.On call
func (_e *PriceIngestorServer_Expecter) mustEmbedUnimplementedPriceIngestorServer() *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	return &PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPriceIngestorServer")}
}

func (_c *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call) Run(run func()) *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call) Return() *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call) RunAndReturn(run func()) *PriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	_c.Run(run)
	return _c
}

// NewPriceIngestorServer creates a new instance of PriceIngestorServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceIngestorServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceIngestorServer {
	mock := &PriceIngestorServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
