// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/carlosgab83/matrix/go/internal/shared/domain"
	mock "github.com/stretchr/testify/mock"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

type Publisher_Expecter struct {
	mock *mock.Mock
}

func (_m *Publisher) EXPECT() *Publisher_Expecter {
	return &Publisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Publisher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Publisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Publisher_Expecter) Close() *Publisher_Close_Call {
	return &Publisher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Publisher_Close_Call) Run(run func()) *Publisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Publisher_Close_Call) Return(_a0 error) *Publisher_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Publisher_Close_Call) RunAndReturn(run func() error) *Publisher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBPrice provides a mock function with given fields: _a0, _a1
func (_m *Publisher) NewDBPrice(_a0 context.Context, _a1 domain.Price) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for NewDBPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Price) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publisher_NewDBPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewDBPrice'
type Publisher_NewDBPrice_Call struct {
	*mock.Call
}

// NewDBPrice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Price
func (_e *Publisher_Expecter) NewDBPrice(_a0 interface{}, _a1 interface{}) *Publisher_NewDBPrice_Call {
	return &Publisher_NewDBPrice_Call{Call: _e.mock.On("NewDBPrice", _a0, _a1)}
}

func (_c *Publisher_NewDBPrice_Call) Run(run func(_a0 context.Context, _a1 domain.Price)) *Publisher_NewDBPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Price))
	})
	return _c
}

func (_c *Publisher_NewDBPrice_Call) Return(_a0 error) *Publisher_NewDBPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Publisher_NewDBPrice_Call) RunAndReturn(run func(context.Context, domain.Price) error) *Publisher_NewDBPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewPublisher creates a new instance of Publisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
