// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/carlosgab83/matrix/go/internal/tank/domain"
	mock "github.com/stretchr/testify/mock"
)

// Receptor is an autogenerated mock type for the Receptor type
type Receptor struct {
	mock.Mock
}

type Receptor_Expecter struct {
	mock *mock.Mock
}

func (_m *Receptor) EXPECT() *Receptor_Expecter {
	return &Receptor_Expecter{mock: &_m.Mock}
}

// BeginConsumption provides a mock function with no fields
func (_m *Receptor) BeginConsumption() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginConsumption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Receptor_BeginConsumption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginConsumption'
type Receptor_BeginConsumption_Call struct {
	*mock.Call
}

// BeginConsumption is a helper method to define mock.On call
func (_e *Receptor_Expecter) BeginConsumption() *Receptor_BeginConsumption_Call {
	return &Receptor_BeginConsumption_Call{Call: _e.mock.On("BeginConsumption")}
}

func (_c *Receptor_BeginConsumption_Call) Run(run func()) *Receptor_BeginConsumption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Receptor_BeginConsumption_Call) Return(_a0 error) *Receptor_BeginConsumption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Receptor_BeginConsumption_Call) RunAndReturn(run func() error) *Receptor_BeginConsumption_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *Receptor) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Receptor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Receptor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Receptor_Expecter) Close() *Receptor_Close_Call {
	return &Receptor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Receptor_Close_Call) Run(run func()) *Receptor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Receptor_Close_Call) Return(_a0 error) *Receptor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Receptor_Close_Call) RunAndReturn(run func() error) *Receptor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveCh provides a mock function with no fields
func (_m *Receptor) ReceiveCh() chan domain.NotificationPayload {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReceiveCh")
	}

	var r0 chan domain.NotificationPayload
	if rf, ok := ret.Get(0).(func() chan domain.NotificationPayload); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan domain.NotificationPayload)
		}
	}

	return r0
}

// Receptor_ReceiveCh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveCh'
type Receptor_ReceiveCh_Call struct {
	*mock.Call
}

// ReceiveCh is a helper method to define mock.On call
func (_e *Receptor_Expecter) ReceiveCh() *Receptor_ReceiveCh_Call {
	return &Receptor_ReceiveCh_Call{Call: _e.mock.On("ReceiveCh")}
}

func (_c *Receptor_ReceiveCh_Call) Run(run func()) *Receptor_ReceiveCh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Receptor_ReceiveCh_Call) Return(_a0 chan domain.NotificationPayload) *Receptor_ReceiveCh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Receptor_ReceiveCh_Call) RunAndReturn(run func() chan domain.NotificationPayload) *Receptor_ReceiveCh_Call {
	_c.Call.Return(run)
	return _c
}

// NewReceptor creates a new instance of Receptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Receptor {
	mock := &Receptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
