// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/carlosgab83/matrix/go/internal/shared/domain"
	mock "github.com/stretchr/testify/mock"
)

// SymbolFetcher is an autogenerated mock type for the SymbolFetcher type
type SymbolFetcher struct {
	mock.Mock
}

type SymbolFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *SymbolFetcher) EXPECT() *SymbolFetcher_Expecter {
	return &SymbolFetcher_Expecter{mock: &_m.Mock}
}

// BTCUSDFetch provides a mock function with given fields: _a0
func (_m *SymbolFetcher) BTCUSDFetch(_a0 context.Context) (*domain.Price, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BTCUSDFetch")
	}

	var r0 *domain.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Price, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Price); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SymbolFetcher_BTCUSDFetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BTCUSDFetch'
type SymbolFetcher_BTCUSDFetch_Call struct {
	*mock.Call
}

// BTCUSDFetch is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *SymbolFetcher_Expecter) BTCUSDFetch(_a0 interface{}) *SymbolFetcher_BTCUSDFetch_Call {
	return &SymbolFetcher_BTCUSDFetch_Call{Call: _e.mock.On("BTCUSDFetch", _a0)}
}

func (_c *SymbolFetcher_BTCUSDFetch_Call) Run(run func(_a0 context.Context)) *SymbolFetcher_BTCUSDFetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SymbolFetcher_BTCUSDFetch_Call) Return(_a0 *domain.Price, _a1 error) *SymbolFetcher_BTCUSDFetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SymbolFetcher_BTCUSDFetch_Call) RunAndReturn(run func(context.Context) (*domain.Price, error)) *SymbolFetcher_BTCUSDFetch_Call {
	_c.Call.Return(run)
	return _c
}

// ETHUSDFetch provides a mock function with given fields: _a0
func (_m *SymbolFetcher) ETHUSDFetch(_a0 context.Context) (*domain.Price, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ETHUSDFetch")
	}

	var r0 *domain.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Price, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Price); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SymbolFetcher_ETHUSDFetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ETHUSDFetch'
type SymbolFetcher_ETHUSDFetch_Call struct {
	*mock.Call
}

// ETHUSDFetch is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *SymbolFetcher_Expecter) ETHUSDFetch(_a0 interface{}) *SymbolFetcher_ETHUSDFetch_Call {
	return &SymbolFetcher_ETHUSDFetch_Call{Call: _e.mock.On("ETHUSDFetch", _a0)}
}

func (_c *SymbolFetcher_ETHUSDFetch_Call) Run(run func(_a0 context.Context)) *SymbolFetcher_ETHUSDFetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SymbolFetcher_ETHUSDFetch_Call) Return(_a0 *domain.Price, _a1 error) *SymbolFetcher_ETHUSDFetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SymbolFetcher_ETHUSDFetch_Call) RunAndReturn(run func(context.Context) (*domain.Price, error)) *SymbolFetcher_ETHUSDFetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewSymbolFetcher creates a new instance of SymbolFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSymbolFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *SymbolFetcher {
	mock := &SymbolFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
