// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePriceIngestorServer is an autogenerated mock type for the UnsafePriceIngestorServer type
type UnsafePriceIngestorServer struct {
	mock.Mock
}

type UnsafePriceIngestorServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafePriceIngestorServer) EXPECT() *UnsafePriceIngestorServer_Expecter {
	return &UnsafePriceIngestorServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedPriceIngestorServer provides a mock function with no fields
func (_m *UnsafePriceIngestorServer) mustEmbedUnimplementedPriceIngestorServer() {
	_m.Called()
}

// UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPriceIngestorServer'
type UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPriceIngestorServer is a helper method to define mock.On call
func (_e *UnsafePriceIngestorServer_Expecter) mustEmbedUnimplementedPriceIngestorServer() *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	return &UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPriceIngestorServer")}
}

func (_c *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call) Run(run func()) *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call) Return() *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call) RunAndReturn(run func()) *UnsafePriceIngestorServer_mustEmbedUnimplementedPriceIngestorServer_Call {
	_c.Run(run)
	return _c
}

// NewUnsafePriceIngestorServer creates a new instance of UnsafePriceIngestorServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePriceIngestorServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePriceIngestorServer {
	mock := &UnsafePriceIngestorServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
