// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ingest_price.proto

package matrix_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceIngestor_IngestPrice_FullMethodName = "/proto.PriceIngestor/IngestPrice"
)

// PriceIngestorClient is the client API for PriceIngestor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceIngestorClient interface {
	IngestPrice(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PriceMessage, IngestResponse], error)
}

type priceIngestorClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceIngestorClient(cc grpc.ClientConnInterface) PriceIngestorClient {
	return &priceIngestorClient{cc}
}

func (c *priceIngestorClient) IngestPrice(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PriceMessage, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceIngestor_ServiceDesc.Streams[0], PriceIngestor_IngestPrice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PriceMessage, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceIngestor_IngestPriceClient = grpc.ClientStreamingClient[PriceMessage, IngestResponse]

// PriceIngestorServer is the server API for PriceIngestor service.
// All implementations must embed UnimplementedPriceIngestorServer
// for forward compatibility.
type PriceIngestorServer interface {
	IngestPrice(grpc.ClientStreamingServer[PriceMessage, IngestResponse]) error
	mustEmbedUnimplementedPriceIngestorServer()
}

// UnimplementedPriceIngestorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceIngestorServer struct{}

func (UnimplementedPriceIngestorServer) IngestPrice(grpc.ClientStreamingServer[PriceMessage, IngestResponse]) error {
	return status.Errorf(codes.Unimplemented, "method IngestPrice not implemented")
}
func (UnimplementedPriceIngestorServer) mustEmbedUnimplementedPriceIngestorServer() {}
func (UnimplementedPriceIngestorServer) testEmbeddedByValue()                       {}

// UnsafePriceIngestorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceIngestorServer will
// result in compilation errors.
type UnsafePriceIngestorServer interface {
	mustEmbedUnimplementedPriceIngestorServer()
}

func RegisterPriceIngestorServer(s grpc.ServiceRegistrar, srv PriceIngestorServer) {
	// If the following call pancis, it indicates UnimplementedPriceIngestorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceIngestor_ServiceDesc, srv)
}

func _PriceIngestor_IngestPrice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PriceIngestorServer).IngestPrice(&grpc.GenericServerStream[PriceMessage, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceIngestor_IngestPriceServer = grpc.ClientStreamingServer[PriceMessage, IngestResponse]

// PriceIngestor_ServiceDesc is the grpc.ServiceDesc for PriceIngestor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceIngestor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PriceIngestor",
	HandlerType: (*PriceIngestorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestPrice",
			Handler:       _PriceIngestor_IngestPrice_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ingest_price.proto",
}
