// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ingest_price.proto

package matrix_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceMessage) Reset() {
	*x = PriceMessage{}
	mi := &file_ingest_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceMessage) ProtoMessage() {}

func (x *PriceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceMessage.ProtoReflect.Descriptor instead.
func (*PriceMessage) Descriptor() ([]byte, []int) {
	return file_ingest_price_proto_rawDescGZIP(), []int{0}
}

func (x *PriceMessage) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceMessage) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PriceMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_ingest_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_ingest_price_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ingest_price_proto protoreflect.FileDescriptor

const file_ingest_price_proto_rawDesc = "" +
	"\n" +
	"\x12ingest_price.proto\x12\x05proto\"v\n" +
	"\fPriceMessage\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"D\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2J\n" +
	"\rPriceIngestor\x129\n" +
	"\vIngestPrice\x12\x13.proto.PriceMessage\x1a\x15.proto.IngestResponseB\x0eZ\fmatrix.protob\x06proto3"

var (
	file_ingest_price_proto_rawDescOnce sync.Once
	file_ingest_price_proto_rawDescData []byte
)

func file_ingest_price_proto_rawDescGZIP() []byte {
	file_ingest_price_proto_rawDescOnce.Do(func() {
		file_ingest_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_price_proto_rawDesc), len(file_ingest_price_proto_rawDesc)))
	})
	return file_ingest_price_proto_rawDescData
}

var file_ingest_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ingest_price_proto_goTypes = []any{
	(*PriceMessage)(nil),   // 0: proto.PriceMessage
	(*IngestResponse)(nil), // 1: proto.IngestResponse
}
var file_ingest_price_proto_depIdxs = []int32{
	0, // 0: proto.PriceIngestor.IngestPrice:input_type -> proto.PriceMessage
	1, // 1: proto.PriceIngestor.IngestPrice:output_type -> proto.IngestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ingest_price_proto_init() }
func file_ingest_price_proto_init() {
	if File_ingest_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_price_proto_rawDesc), len(file_ingest_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_price_proto_goTypes,
		DependencyIndexes: file_ingest_price_proto_depIdxs,
		MessageInfos:      file_ingest_price_proto_msgTypes,
	}.Build()
	File_ingest_price_proto = out.File
	file_ingest_price_proto_goTypes = nil
	file_ingest_price_proto_depIdxs = nil
}
