// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ingest_price.proto

package matrix_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceIngestor_IngestPrice_FullMethodName = "/proto.PriceIngestor/IngestPrice"
)

// PriceIngestorClient is the client API for PriceIngestor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceIngestorClient interface {
	IngestPrice(ctx context.Context, in *PriceMessage, opts ...grpc.CallOption) (*IngestResponse, error)
}

type priceIngestorClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceIngestorClient(cc grpc.ClientConnInterface) PriceIngestorClient {
	return &priceIngestorClient{cc}
}

func (c *priceIngestorClient) IngestPrice(ctx context.Context, in *PriceMessage, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, PriceIngestor_IngestPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceIngestorServer is the server API for PriceIngestor service.
// All implementations must embed UnimplementedPriceIngestorServer
// for forward compatibility.
type PriceIngestorServer interface {
	IngestPrice(context.Context, *PriceMessage) (*IngestResponse, error)
	mustEmbedUnimplementedPriceIngestorServer()
}

// UnimplementedPriceIngestorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceIngestorServer struct{}

func (UnimplementedPriceIngestorServer) IngestPrice(context.Context, *PriceMessage) (*IngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestPrice not implemented")
}
func (UnimplementedPriceIngestorServer) mustEmbedUnimplementedPriceIngestorServer() {}
func (UnimplementedPriceIngestorServer) testEmbeddedByValue()                       {}

// UnsafePriceIngestorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceIngestorServer will
// result in compilation errors.
type UnsafePriceIngestorServer interface {
	mustEmbedUnimplementedPriceIngestorServer()
}

func RegisterPriceIngestorServer(s grpc.ServiceRegistrar, srv PriceIngestorServer) {
	// If the following call pancis, it indicates UnimplementedPriceIngestorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceIngestor_ServiceDesc, srv)
}

func _PriceIngestor_IngestPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceIngestorServer).IngestPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceIngestor_IngestPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceIngestorServer).IngestPrice(ctx, req.(*PriceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceIngestor_ServiceDesc is the grpc.ServiceDesc for PriceIngestor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceIngestor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PriceIngestor",
	HandlerType: (*PriceIngestorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestPrice",
			Handler:    _PriceIngestor_IngestPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingest_price.proto",
}
